FROM confluentinc/cp-zookeeper:6.2.0

# Copy custom configurations
COPY zookeeper.properties /etc/kafka/zookeeper.properties

# Expose ZooKeeper ports
EXPOSE 2181 2888 3888

# Start ZooKeeper server
CMD ["zookeeper-server-start", "/etc/kafka/zookeeper.properties"]
